config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'new', to: 'games#new'
  get 'end', to: 'games#end'
  post 'score', to: 'games#score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController
  def new
    alphabet = ('A'..'Z').to_a
    alphabet += alphabet
    @letters = alphabet.sample(10)
  end

  def check_grid?(attempt, grid)
    attempt.upcase!
    attempt_chars = attempt.split('')
    counter = 0
    attempt_chars.each { |char| counter += 1 if grid.include?(char) }
    counter == attempt_chars.length
  end

  def doubles?(attempt, grid)
    # if a letter appears twice in the attempt but only once in the grid
    attempt_chars = attempt.upcase.chars
    return_value = attempt_chars.find do |letter|
      attempt_chars.count(letter) > grid.count(letter)
    end
    return_value.nil? ? (return_value = false) : (return_value = true)
    return return_value
  end

  def english_word?(attempt)
    base_url = "https://wagon-dictionary.herokuapp.com/"
    word_url = base_url + attempt

    word_file = open(word_url).read
    word = JSON.parse(word_file)

    word['found'] == true
  end

  def end
    reset_session
    session[:score] = 0
  end

  def score
    @answer = params[:answer]
    @letters = params[:letters]
    @score = 0
    if @answer
      if (check_grid?(@answer, @letters) && english_word?(@answer)) && !doubles?(@answer, @letters)
        @result = "Well done #{@answer} was an excellent find!"
        @score += (@answer.length ** 2) + 3
        session[:score] += @score
      elsif !english_word?(@answer)
        @result = "Sorry but #{@answer} is not an English word."
      elsif !check_grid?(@answer, @letters)
        @result = "Sorry but #{@answer} is not in the grid."
      elsif doubles?(@answer, @letters)
        @result = "Sorry but #{@answer} contains more than 1 of the provided letters."
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/end.html.erb
<h1>Game Finished!</h1>
<%= link_to 'Play Again', new_path, class:'link' %>

app/views/games/new.html.erb
<h1>New game</h1>

<div class="letters-container">
  <% @letters.each do |letter| %>
    <p class="letter"><%= letter %></p>
  <% end %>
</div>

<h3>What is the longest word you can find?</h3>

<div class="form-container">
  <form action="score" method="POST" class="form">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= hidden_field_tag 'letters', @letters %>
    <input type="text" name="answer" class="input-text">
    <input type="submit" value="Play" class="submit">
  </form>
</div>

app/views/games/score.html.erb
<h1>Your results</h1>
<h2><%= @result %></h2>
<h4>Your score is: <%= session[:score] %></h4>
<%= link_to 'Play Another Round', new_path, class:'link' %>
<%= link_to 'End Game', end_path, class:'link' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>